### ISSUE TITLE
Google Analytics IP masking

### ISSUE THREAD

**Issue by sbradl** [d6y/liftmodules-googleanalytics#2]
I think in germany your end-user notification trigger is not enough to be compliant with the laws. IP Masking needs to be enabled using "_gaq.push([ '_gat._anonymizeIp' ]);" It would be nice to enable ip anonymization with a parameter.

**Comment by d6y** [comment]
Thank you - I'll try to find a way to control what's pushed onto the global object.

Reference for myself:
- https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApi_gat#_gat._anonymizeIp

**Comment by sbradl** [comment]
Maybe you can have a look at my code. I have a similar ga snippet.

Snippet:
https://github.com/sbradl/liftedcontent-util/blob/master/src/main/scala/eu/sbradl/liftedcontent/util/snippet/GoogleAnalytics.scala

Usage example:
`<script data-lift="GoogleAnalytics?id=UA-xyz&anonymize=true"></script>`

**Comment by d6y** [comment]
After 5 years, I don't think anyone is stepping forward to fix this, and the GA environment and GDPR has changed so much....so I'll close this for now. If anyone wants to take it on....please feel free to re-open.
