### ISSUE TITLE
Universal Analytics: ga.js to analytics.js option

### ISSUE THREAD

**Issue by jcabrra** [d6y/liftmodules-googleanalytics#4]
https://developers.google.com/analytics/devguides/collection/upgrade/

It'll be neat to have an option to use analytics.js (or Universal Analytics.) 

analytics.js:
https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs#snippet

**Comment by d6y** [comment]
Thanks for spotting that: sounds like a good idea.

**Comment by d6y** [comment]
Fixed by: https://github.com/d6y/liftmodules-googleanalytics/pull/8
